version: '3'
services:
  pg_database:
    image: postgres:13-alpine
    container_name: pg_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:${POSTGRES_PORT}

  redis:
    image: redis:7.2.3-alpine
    restart: always
    expose:
      - 6379

  app:
    build:
      context: url_service
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - pg_database
  
  worker:
    build:
      context: consumer
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - redis
      - pg_database

volumes:
  postgres_data: