name: linters workflow 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: --line-length 79
      - name: Run MyPy with HTML report
        uses: jpetrucciani/mypy-check@master
        with:
          requirements: -r requirements.txt
          mypy_flags: '--config-file .mypy.ini --html-report coverage_report'
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: mypy-coverage-report
          path: coverage_report
